### ISSUE TITLE
Crashes on invalid yaml

### ISSUE THREAD

**Issue by markusdregi** [equinor/configsuite-tui#34]
When trying to load the following config using the predefined `Named dict` schema I get an exception `yaml.parser.ParserError: while parsing a flow node`.

```
name: Markus
hobby: fdsfds
age: 123213
active: false
score: 12
birthday: 2000-01-01
last_seen: 2000-01-01 00:00:00
list_of_dogs: [}
dict_of_random_info:
  a: '14'
  b: hrtgfd
```
